
RESPONSEALREADYEXISTS=0
RESPONSECORRECTLYUPLOADED=1
RESPONSEDOESNTEXIST=2
RESPONSETRAJECTORY=3
REQUESTEXISTANCE = 4
REQUESTUPLOAD = 5
REQUESTTRAJECTORY=6
STATELEGALPROBLEMS= 7;
STATEMISSING=8;
BUFFER_SIZE= 65536
FLANN_INDEX_LSH= 6
ENCODING = 'utf-8'
PERSONIMAGECONTAINERFOLDER= "/PersonImageContainer"
CROPIMAGECONTAINERFOLDER= "/CropImageContainer"
BIGPICIMAGECONTAINERFOLDER= "/BigPicImageContainer"
HOST_CMC="0.0.0.0"
QUEUE_RPC="http_rpc"
